#!/sbin/sh

# configure.sh by SuperR. @XDA

# Do not edit this file unless you know what you are doing

cp /tmp/install/busybox /sbin/
chmod 755 /sbin/busybox

rm -f /tmp/config

SLOT=$(getprop ro.boot.slot_suffix)
if [ -z $SLOT ]; then
	SLOT=_$(getprop ro.boot.slot)
	if [ $SLOT = "_" ]; then
		SLOT=
	fi
fi
if [ -z $SLOT ]; then
	SLOT=$(cat /proc/cmdline 2>/dev/null | tr ' ' '\n' | grep slot | grep -v simslot | cut -d'=' -f2)
fi
if [ ! -z $SLOT ]; then
	echo "slotnum=$SLOT" >> /tmp/config
fi

SYSTEMBLOCK=$(find /dev/block | grep -i "system$SLOT" | head -n 1)
if [ -z $SYSTEMBLOCK ]; then
	for FSTAB in /etc/*fstab*; do
		SYSTEMBLOCK=$(grep -v '#' $FSTAB | grep -E '/system[^a-zA-Z]' | grep -oE '/dev/[a-zA-Z0-9_./-]*')
		if [ ! -z $SYSTEMBLOCK ]; then
			break
		fi
	done
fi
if [ ! -z $SYSTEMBLOCK ] && [ $(readlink -f $SYSTEMBLOCK) ]; then
	BYNAME=$(dirname $SYSTEMBLOCK)
	echo "byname=$BYNAME" >> /tmp/config
else
	exit 1
fi

for i in system SYSTEM APP; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "system=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done
for i in vendor VENDOR VNR; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "vendor=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done
for i in userdata USERDATA UDA; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "data=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done
for i in boot BOOT LNX; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "boot=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done

for i in dtbo DTBO; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "dtbo=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done
for i in vbmeta VBMETA; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "vbmeta=$BYNAME/$i$SLOT" >> /tmp/config
		break
	fi
done
for i in abl; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "abl=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in bluetooth; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "bluetooth=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in cmnlib; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "cmnlib=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in cmnlib64; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "cmnlib64=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in devcfg; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "devcfg=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in dsp; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "dsp=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in hyp; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "hyp=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in imagefv; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "imagefv=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in keymaster; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "keymaster=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in modem; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "modem=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in product; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "product=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in qupfw; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "qupfw=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in rpm; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "rpm=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in storsec; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "storsec=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in tz; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "tz=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in uefisecapp; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "uefisecapp=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in xbl; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "xbl=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
for i in xbl_config; do
	if [ $(readlink $BYNAME/$i$SLOT) ]; then
		echo "xbl_config=$BYNAME/$i$SLOT" >> /tmp/config
	fi
done
